repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-json
  - id: check-toml
  - id: check-yaml
  - id: check-added-large-files
  - id: detect-private-key
  - id: pretty-format-json
    args: ["--autofix", "--indent=4", "--no-sort-keys", "--no-ensure-ascii"]
- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
  - id: black
  - id: black-jupyter
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort
- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    args: ["--rcfile=.pylintrc"]
    language: system
    types: [python]
    require_serial: true
  - id: pytest-check
    name: pytest-check
    entry: pytest
    stages: [push]
    language: system
    pass_filenames: false
    always_run: true
