"""
"Signaux Faibles" project package for company failure prediction.

* ``config/`` - Configuration and model parameters that will be used during execution.
* ``__init__.py`` - Some data-related variables definitions.
* ``__main__.py`` - Main entry point script, which can be used to launch end-to-end
  predictions.
* ``evaluation.py`` - Scores computations.
* ``exploration.py`` - Data exploration-dedicated functions.
* ``io.py`` - I/O functions.
* ``model.py`` - Model utilities and classes.
* ``predictions.py`` - Post-process model predictions (generation of alert levels,
  tailoring, etc.)
* ``sampler.py`` - Data sampling functions.
* ``transform.py`` - Utilities and classes for handling and transforming datasets.
* ``utils.py`` - Utility functions for spark session and data handling.
"""

DGFIP_VARIABLES = [
    "siren",
    "date_deb_exercice",
    "date_fin_exercice",
    "MNT_AF_CA",
    "MNT_AF_SIG_EBE",
    "RTO_AF_SOLV_ENDT_NET",
    "MNT_AF_BPAT_PASSIF_K_PROPRES",
    "MNT_AF_SIG_RCAI",
    "MNT_AF_BFONC_TRESORERIE",
    "RTO_AF_AUTO_FINANCIERE",
    "RTO_AF_SOLV_INDP_FI",
    "MNT_AF_BFONC_ACTIF_TRESORERIE",
    "MNT_AF_BFONC_PASSIF_TRESORERIE",
    "MNT_AF_BPAT_ACTIF_SUP1AN",
    "MNT_AF_BPAT_ACTIF_STOCKS",
    "MNT_AF_BPAT_ACTIF_DISPO",
    "RTO_AF_SOLV_ENDT_BRUT",
    "MNT_AF_BFONC_RESSOUR_STABL",
    "MNT_AF_BFONC_FRNG",
    "MNT_AF_BPAT_ACTIF_CREANCES",
    "RTO_AF_SOLV_SOLVABILITE",
    "RTO_AF_SOLV_LQDT_RESTRINTE",
    "RTO_AF_STRUCT_FIN_IMM",
    "RTO_AF_SOLIDITE_FINANCIERE",
    "TX_MOY_TVA_COL",
    "NBR_JOUR_RGLT_CLI",
    "NBR_JOUR_RGLT_FRS",
    "TOT_CREA_CHAV_MOINS1AN",
    "TOT_DET_PDTAV_MOINS1AN",
    "PCT_AF_SOLV_LQDT_GEN",
    "PCT_REND_EXPL",
    "RTO_MG_ACHAT_REV",
    "PCT_CHARG_EXTE_CA_NET",
    "PCT_INDEP_FIN",
    "PCT_PDS_INTERET",
    "NBR_JOUR_ROTA_STK",
    "RTO_INVEST_CA",
    "RTO_TVA_COL_FR",
    "D_CMPT_COUR_ASSO_DEB",
    "D_CMPT_COUR_ASSO_CRED",
    "RTO_TVA_DEDUC_ACH",
    "RTO_TVA_DECUC_TVA_COL",
    "D_CR_250_EXPL_SALAIRE",
    "D_CR_252_EXPL_CH_SOC",
    "MNT_AF_SIG_EBE_RET",
    "MNT_AF_BFONC_BFR",
    "RTO_AF_RATIO_RENT_MBE",
    "RTO_AF_RENT_ECO",
]

ETL_FILES = [
    "etl_associe-ref_groupe_france",
    "etl_decla-declarations_af",
    "etl_decla-declarations_indmap",
    "etl_refent_oracle-t_jugement_histo",
    "etl_rn.d2053_pdt_ch_excep_view",
    "etl_rn.d2053_pdt_ch_exercice_ant_view",
    "etl_rn.d2056_detail_autre_prov_view",
    "etl_rn.d2056_detail_deprec_view",
    "etl_rn.d2056_detail_hausse_prix_view",
    "etl_rn.d2056_detail_immo_fi_view",
    "etl_rn.d2056_detail_impot_view",
    "etl_rn.d2056_detail_risq_charge_view",
    "etl_rn.d2058a_detail_deduc_view",
    "etl_rn.d2058a_detail_reinteg_view",
    "etl_rn.d2058b_detail_ch_a_payer_view",
    "etl_rn.d2058b_detail_prov_deprec_view",
    "etl_rn.d2058b_detail_prov_risq_view",
    "etl_rn.d2059a_detail_divers_view",
    "etl_rn.d2059a_immobilisation_pmv_view",
    "etl_rn.d2059b_detail_fusion_apport_view",
    "etl_rn.d2059f_associe_pm_view",
    "etl_rn.d2059f_associe_pp_view",
    "etl_rn.d2059g_filiale_view",
    "etl_rn.liasse_rn_view",
    "etl_rn.v_matrice_epro_rn",
    "etl_rsi.d2033b_result_deduc_view",
    "etl_rsi.d2033b_result_reint_view",
    "etl_rsi.d2033c_pv_mv_view",
    "etl_rsi.d2033d_dotation_ventil_view",
    "etl_rsi.d2033f_associe_pm_view",
    "etl_rsi.d2033f_associe_pp_view",
    "etl_rsi.d2033g_filiale_view",
    "etl_rsi.liasse_rsi_view",
    "etl_rsi.v_matrice_epro_rsi",
    "etl_tva.d3310a_eau_minerale_view",
    "etl_tva.d3310a_geothermie_view",
    "etl_tva.d3310a_hydrocarbure_view",
    "etl_tva.d3310ter_tva_secteur_view",
    "etl_tva.d3517s_eau_minerale_view",
    "etl_tva.d3517s_geothermie_view",
    "etl_tva.d3517s_hydrocarbure_view",
    "etl_tva.liasse_tva_3310a_comm_view",
    "etl_tva.liasse_tva_3310a_view",
    "etl_tva.liasse_tva_3310ter_comm_view",
    "etl_tva.liasse_tva_3310ter_view",
    "etl_tva.liasse_tva_3517ddr_comm_view",
    "etl_tva.liasse_tva_3517ddr_view",
    "etl_tva.liasse_tva_ca12_comm_view",
    "etl_tva.liasse_tva_ca12_view",
    "etl_tva.liasse_tva_ca12a_comm_view",
    "etl_tva.liasse_tva_ca12a_view",
    "etl_tva.liasse_tva_ca3_comm_view",
    "etl_tva.liasse_tva_ca3_view",
    "etl_tva.v_matrice_epro_tva",
    "pub_medoc_oracle-t_defaillance",
    "pub_refent-t_ref_entreprise",
    "pub_refent-t_ref_etablissements",
    "pub_refer-t_ref_code_nace_complet",
    "pub_refer-t_ref_lib_forme_juridique",
]

ORACLE_FILES = ["pub_risq_oracle.t_dar", "pub_risq_oracle.t_art"]
